name: Deploy Cloudformation Templates

on:
  push:
    branches:
      - main

env:
  STACK_NAME: aws-services-security-automation
  STACK_NAME_ROUTE53: aws-services-security-automation-route-53
  S3_BUCKET_NAME: aws-services-security-automation
  S3_BUCKET_NAME_ROUTE_53: aws-services-security-automation-route-53
  AWS_DEFAULT_REGION: eu-central-1 

jobs:
  deploy_templates:
    runs-on: ubuntu-latest
    environment: develop
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install SAM CLI
      run: pip install aws-sam-cli

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_DEFAULT_REGION }}

    # First Template
    - name: SAM Build for Route53
      run: sam build --debug
      working-directory: ./route53-public-http-hosts

    - name: Change Directory for Route53
      run: cd .aws-sam/build
      working-directory: ./route53-public-http-hosts

    - name: SAM Deploy for Route53
      run: |
        sam deploy --stack-name ${{ env.STACK_NAME_ROUTE53 }} --region ${{ env.AWS_DEFAULT_REGION }} --template-file .aws-sam/build/template.yaml --capabilities CAPABILITY_IAM --no-confirm-changeset --resolve-s3
      working-directory: ./route53-public-http-hosts

    # Second Template
    - name: SAM Build for Services Security
      run: sam build --debug
      working-directory: ./services-security

    - name: Change Directory for Services Security
      run: cd .aws-sam/build
      working-directory: ./services-security

    - name: SAM Deploy for Services Security
      run: |
        sam deploy --stack-name ${{ env.STACK_NAME }} --region ${{ env.AWS_DEFAULT_REGION }} --template-file .aws-sam/build/template.yaml --capabilities CAPABILITY_IAM --no-confirm-changeset --resolve-s3
      working-directory: ./services-security

